# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install dependencies
WORKDIR /app

# Install build dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libffi-dev build-essential && \
    rm -rf /var/lib/apt/lists/*

# Copy project files
COPY pyproject.toml .
COPY src ./src
COPY README.md .

# Install Python dependencies
RUN pip install --no-cache-dir .

# Set default environment variables for HTTP transport
ENV MCP_TRANSPORT=http
ENV MCP_HOST=0.0.0.0
ENV MCP_PORT=8000

# Expose the MCP port
EXPOSE 8000

# Set default entrypoint
ENTRYPOINT ["amazing-marvin-mcp"]