name: Deploy to Smithery

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Smithery CLI
      run: npm install -g @smithery/cli
      
    - name: Deploy to Smithery
      env:
        SMITHERY_API_KEY: ${{ secrets.SMITHERY_API_KEY }}
      run: |
        echo "$SMITHERY_API_KEY" | npx @smithery/cli login
        npx @smithery/cli build
        npx @smithery/cli deploy